version: "3.9"

services:

  neo4j:
    image: neo4j:5

    container_name: mulenetx-neo4j

    environment:
      NEO4J_AUTH: neo4j/password

    ports:
      - "7474:7474"
      - "7687:7687"
      
  backend:
    build:
      context: ../backend
      dockerfile: ../docker/backend.Dockerfile

    container_name: mulenetx-backend

    ports:
      - "8000:8000"

    restart: unless-stopped
